Importing Necessary Libraries and Fetching Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv', encoding = 'latin-1')

In [3]:
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

Exploratory Data Analysis

In [4]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [5]:
df.describe()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
count,5572,5572,50,12,6
unique,2,5169,43,10,5
top,ham,"Sorry, I'll call later","bt not his girlfrnd... G o o d n i g h t . . .@""","MK17 92H. 450Ppw 16""","GNT:-)"""
freq,4825,30,3,2,2

In [6]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [7]:
df.drop('Unnamed: 2', axis = 1, inplace = True)

In [8]:
df.drop('Unnamed: 3', axis = 1, inplace = True)

In [9]:
df.drop('Unnamed: 4', axis = 1, inplace = True)

In [10]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

Data Cleaning

In [11]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download necessary NLTK resources (only once)
nltk.download('stopwords')
nltk.download('wordnet')

# Initialize lemmatizer and stopwords
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sayan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Sayan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [12]:
def clean_text(text):
    if not isinstance(text, str):  # Handle NaN values
        return ""

    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\W', ' ', text)  # Remove special characters
    text = re.sub(r'\s+', ' ', text)  # Remove extra spaces
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]  # Remove stopwords and lemmatize
    return ' '.join(words)

In [13]:
df['Cleaned_Text'] = df['v2'].apply(clean_text)

In [14]:
df

,v1,v2,Cleaned_Text
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah think go usf life around though
...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,2nd time tried 2 contact u u å 750 pound prize...
5568,ham,Will Ì_ b going to esplanade fr home?,ì_ b going esplanade fr home
5569,ham,"Pity, * was in mood for that. So...any other s...",pity mood suggestion
5570,ham,The guy did some bitching but I acted like i'd...,guy bitching acted like interested buying some...
5571,ham,Rofl. Its true to its name,rofl true name

Model Training

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X_train, X_test, Y_train, Y_test = train_test_split(df['Cleaned_Text'], df['v1'], test_size = 0.20, random_state = 42)

tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=10000)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

X_train_dense = X_train_tfidf.toarray()
X_test_dense = X_test_tfidf.toarray()

Y = np.array(Y_train)

In [16]:
Y_train

1978     ham
3989    spam
3935     ham
4078     ham
4086    spam
        ...
3772     ham
5191     ham
5226     ham
5390     ham
860      ham
Name: v1, Length: 4457, dtype: object

In [17]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

In [18]:
model.fit(X_train_dense, Y)

GaussianNB()

In [19]:
Y_pred = model.predict(X_test_dense)

In [20]:
Y_pred

array(['ham', 'ham', 'spam', ..., 'ham', 'spam', 'spam'],
      shape=(1115,), dtype='<U4')

In [21]:
from sklearn.metrics import accuracy_score

print('Accuracy Score: ', accuracy_score(Y_test, Y_pred))

Accuracy Score:  0.8798206278026905

Testing Predictions With Sample Data

In [24]:
def predict_spam(message):
    cleaned = clean_text(message)
    vectorized = tfidf_vectorizer.transform([cleaned]).toarray()
    prediction = model.predict(vectorized)[0]
    return prediction

In [28]:
test_messages = [
    "Congratulations!!! You have WON a $1000 gift card",
    "Hi, can we reschedule our meeting?",
    "Earn money from home easily",
    "Your OTP is 123456",
]

for msg in test_messages:
    print(msg, "->", predict_spam(msg))

Congratulations!!! You have WON a $1000 gift card -> spam
Hi, can we reschedule our meeting? -> ham
Earn money from home easily -> ham
Your OTP is 123456 -> spam